version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  show-html:
    lang: python3
    handler: ./show-html
    image: dmc/show-html:latest
    environment:
      content_type: text/html

